<?php
$translate = $this->plugin('translate');
$navDepth = (int) $this->themeSetting('nav_depth') ? (int) $this->themeSetting('nav_depth') -1 : -1;
?>

<header class="main-header">

	<div class="main-header__top-bar container">
		<div class="main-header__search-area main-header__search-area--top">
			<a class="main-header__advanced-search" href="<?php echo $site->url() . '/item/search'; ?>"><?php echo $translate('Advanced search'); ?></a>
			<div class="main-header__search-form">
				<?php echo $this->partial('common/search-form'); ?>
			</div>
		</div>
		<?php echo $this->partial('common/user-bar', ['user' => $this->identity()]); ?>
	</div>
	<hr class="alignfull">

	<div class="main-header__main-bar container">
		<div class="main-header__site-title">
			<a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml( $site->title() ); ?>" />
			<?php endif; ?>
				<span class="main-header__site-name"><?php echo $this->escapeHtml( $site->title() ); ?></span>
			</a>
		</div>

		<?php if ($this->themeSetting('header_menu')): ?>
		<nav class="main-navigation">
			<div class="main-navigation__container">
				<?php
				echo $site->publicNav()->menu()->renderMenu(null, [
					'addClassToListItem' => true,
					'maxDepth' => $navDepth
				]);
				?>
			</div>
			<div class="main-navigation__toggle"
				 tabindex="0"
				 role="button"
				 aria-expanded="false"
				 aria-controls="menu-drawer"
				 aria-labelledby="menu-backer">
				<span></span>
				<span></span>
				<span></span>
			</div>
		</nav>

		<?php echo $this->partial('common/menu-drawer'); ?>
		<?php endif; ?>

		<div class="main-header__search-area main-header__search-area--compact">
			<div class="main-header__search-form">
				<?php echo $this->partial('common/search-form'); ?>
			</div>
		</div>
	</div>

</header>
